-- =====================================================================
-- MJM Portal · Maintenance cases (CMMS 2)
-- Target: the SAME Supabase project as MachTrek. New objects only
-- (machinery_ prefix) + one new column on machinery_whatsapp_messages.
-- Safe to run more than once.
--
-- How to run: Supabase dashboard → SQL Editor → paste this whole file → Run.
-- Run 20260929120000_whatsapp_photo_inbox.sql first.
--
-- A case groups WhatsApp texts and photos about one breakdown. The webhook
-- creates a case for a new report and replies with its number (#12); later
-- messages join it by replying to that WhatsApp message or by writing #12.
-- =====================================================================

create table if not exists public.machinery_cases (
  id               uuid primary key default gen_random_uuid(),
  case_no          bigint generated by default as identity unique,  -- shown as #12
  wa_from          text not null,                 -- who opened the case (digits incl. country code)
  sender_name      text,
  machine_name     text,
  problem          text,
  status           text not null default 'pending' check (status in ('pending', 'solved')),
  opened_at        timestamptz not null default now(),
  solved_at        timestamptz,
  solved_by        uuid references auth.users (id) on delete set null,
  solved_by_email  text,
  ack_message_id   text,                          -- our "Case #12 created" WhatsApp message; replies to it join the case
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists machinery_cases_status_idx on public.machinery_cases (status, opened_at desc);
create index if not exists machinery_cases_from_idx   on public.machinery_cases (wa_from, opened_at desc);
create index if not exists machinery_cases_ack_idx    on public.machinery_cases (ack_message_id);

drop trigger if exists machinery_cases_touch on public.machinery_cases;
create trigger machinery_cases_touch
  before update on public.machinery_cases
  for each row execute function public.machinery_touch_updated_at();

alter table public.machinery_whatsapp_messages
  add column if not exists case_id uuid references public.machinery_cases (id) on delete set null;
create index if not exists machinery_wa_msg_case_idx on public.machinery_whatsapp_messages (case_id);
create index if not exists machinery_wa_msg_ack_idx  on public.machinery_whatsapp_messages (ack_message_id);

-- Browser: portal admins read cases and may edit machine name / problem.
-- Status changes go through the RPC below so "solved by" is always the real user.
alter table public.machinery_cases enable row level security;
revoke all on public.machinery_cases from anon, authenticated;
grant select on public.machinery_cases to authenticated;
grant update (machine_name, problem) on public.machinery_cases to authenticated;

drop policy if exists "cases_admin_read" on public.machinery_cases;
create policy "cases_admin_read" on public.machinery_cases
  for select to authenticated
  using (public.is_machinery_portal_admin());

drop policy if exists "cases_admin_edit" on public.machinery_cases;
create policy "cases_admin_edit" on public.machinery_cases
  for update to authenticated
  using (public.is_machinery_portal_admin())
  with check (public.is_machinery_portal_admin());

create or replace function public.machinery_set_case_solved(p_id uuid, p_solved boolean)
returns public.machinery_cases
language plpgsql security definer
set search_path = public
as $$
declare
  c public.machinery_cases;
begin
  if not public.is_machinery_portal_admin() then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  update public.machinery_cases
     set status          = case when p_solved then 'solved' else 'pending' end,
         solved_at       = case when p_solved then now() else null end,
         solved_by       = case when p_solved then auth.uid() else null end,
         solved_by_email = case when p_solved then (select email from auth.users where id = auth.uid()) else null end
   where id = p_id
  returning * into c;
  if c.id is null then
    raise exception 'case not found' using errcode = 'P0002';
  end if;
  return c;
end $$;
revoke all on function public.machinery_set_case_solved(uuid, boolean) from public, anon;
grant execute on function public.machinery_set_case_solved(uuid, boolean) to authenticated;

-- One-time: give every earlier saved text/photo its own case (keeps its
-- reviewed state as solved). Messages already in a case are skipped.
do $$
declare
  m record;
  new_id uuid;
begin
  for m in
    select * from public.machinery_whatsapp_messages
     where case_id is null and status = 'saved' and message_type in ('text', 'image')
     order by received_at
  loop
    insert into public.machinery_cases (wa_from, sender_name, problem, opened_at, status, solved_at, solved_by, solved_by_email)
    values (m.wa_from, m.sender_name, m.caption, m.received_at,
            case when m.reviewed_at is null then 'pending' else 'solved' end,
            m.reviewed_at, m.reviewed_by, m.reviewed_by_email)
    returning id into new_id;
    update public.machinery_whatsapp_messages set case_id = new_id where id = m.id;
  end loop;
end $$;

-- Shows the cases (newest first).
select case_no, machine_name, problem, status, opened_at from public.machinery_cases order by opened_at desc limit 20;
